/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>

/* Header for class com_xindany_OpenCvUtil */

/*
 * Class:     com_xindany_OpenCvUtil
 * Method:    jiaozheng
 * Signature: ([III)[I
 */


#ifndef _Included_com_xindany_OpenCvUtil
#define _Included_com_xindany_OpenCvUtil
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jintArray JNICALL Java_com_xindany_OpenCvUtil_jiaozheng
  (JNIEnv *env, jobject obj, jintArray buf, int w, int h){

  }

/*
 * Class:     com_xindany_OpenCvUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xindany_OpenCvUtil_getString
  (JNIEnv *env, jobject obj){
       return env->NewStringUTF((char *)"This just a test for Android Studio NDK JNI developer!");
  }


#ifdef __cplusplus
}
#endif
#endif