/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xindany_OpenCvUtil */

#ifndef _Included_com_xindany_OpenCvUtil
#define _Included_com_xindany_OpenCvUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xindany_OpenCvUtil
 * Method:    jiaozheng
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_xindany_OpenCvUtil_jiaozheng
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     com_xindany_OpenCvUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xindany_OpenCvUtil_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
